# Generated by Django 4.2.16 on 2024-09-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topoic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='topoic',
            new_name='topic',
        ),
    ]
